project:
  type: website
  output-dir: build

website:
  title: "LI Yifeng's Blog"
  site-url: "https://blog.yifen9.li"
  description: "LI Yifeng's Blog"
  repo-url: https://github.com/yifen9/blog.yifen9.li
  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
    right:
      - icon: person
        href: https://yifen9.li
      - icon: github
        href: https://github.com/yifen9/blog.yifen9.li
      - icon: rss
        href: index.xml
      
  page-footer:
    left: |
      <img src="https://counter.clarelab.moe/@www-yifeng-li?name=www-yifeng-li&theme=sketch-1&padding=8&offset=0&align=top&scale=0.2&pixelated=1&darkmode=0" alt=":counter" loading="lazy"/>
    center: |
      © {{< now year >}} <a href="https://yifen9.li">LI Yifeng</a>
    right:
      - text: "GitHub"
        href: https://github.com
      - text: "Quarto"
        href: https://quarto.org

format:
  html:
    css: styles.css
    theme: [cosmo, theme.scss]
